stages:
  - terraform
  - build
  - upload

variables:
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"

###############################################
# TERRAFORM DEPLOY
###############################################
terraform_deploy:
  stage: terraform
  image: hashicorp/terraform:1.6.0
  script:
    - terraform init
    - terraform plan
    - terraform apply -auto-approve

###############################################
# BUILD LAMBDA ZIP
###############################################
build_lambda:
  stage: build
  image: python:3.10
  script:
    - apt-get update -y
    - apt-get install -y zip
    - cd lambda_ingestion_code
    - pip install -r requirements.txt -t package
    - cp lambda_handler.py package/
    - cd package
    - zip -r ../lambda.zip .
  artifacts:
    paths:
      - lambda_ingestion_code/lambda.zip

###############################################
# UPLOAD SCRIPTS TO S3
###############################################
upload_scripts:
  stage: upload
  image: amazon/aws-cli:2.15
  script:
    - aws s3 cp lambda_ingestion_code/lambda.zip s3://$SCRIPTS_BUCKET/lambda/lambda.zip
    - aws s3 cp etl_scripts/weather_etl.py s3://$SCRIPTS_BUCKET/etl/weather_etl.py
