stages:
  - terraform_plan
  - terraform_apply
  - build
  - upload
  - terraform_lambda

terraform_plan:
  stage: terraform_plan
  before_script:
    - terraform init
  script:
    - terraform plan -out=tfplan -var="deploy_lambda=false"
  artifacts:
    paths:
      - tfplan

terraform_apply:
  stage: terraform_apply
  when: manual
  before_script:
    - terraform init
  script:
    - terraform apply -auto-approve tfplan
  dependencies:
    - terraform_plan

build_lambda:
  stage: build
  image: python:3.11
  script:
    - apt-get update && apt-get install -y zip
    - cd lambda_ingestion_code && zip -r ../lambda.zip .
  artifacts:
    paths:
      - lambda.zip

upload_scripts:
  stage: upload
  image:
    name: amazon/aws-cli:latest
    entrypoint: [""]
  script:
    - aws s3 cp lambda.zip s3://$SCRIPTS_BUCKET/lambda/lambda.zip

terraform_lambda:
  stage: terraform_lambda
  before_script:
    - terraform init
  script:
    - terraform apply -auto-approve -var="deploy_lambda=true"
