image:
  name: hashicorp/terraform:1.6.0
  entrypoint: [""]

stages:
  - validate
  - plan
  - apply

variables:
  TF_IN_AUTOMATION: "true"

###############################################
# 1. TERRAFORM FORMAT + VALIDATE
###############################################
terraform_validate:
  stage: validate
  script:
    - terraform init -backend=false
    - terraform fmt -check
    - terraform validate

###############################################
# 2. TERRAFORM PLAN
###############################################
terraform_plan:
  stage: plan
  script:
    - terraform init
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - tfplan

###############################################
# 3. TERRAFORM APPLY
###############################################
terraform_apply:
  stage: apply
  script:
    - terraform init
    - terraform apply -auto-approve tfplan
  dependencies:
    - terraform_plan
  when: manual
